=== echeu/wincc-srtm/SRTM_Monitor_EC-01/fwComps/help/en_US.utf8/AlarmHelp/resource/fwAlarmHelp.dtd
<!--
(c) Copyright CERN 2005. All rights not expressly granted are reserved.
icecontrols.support@cern.ch

SPDX-License-Identifier: LGPL-3.0-only
-->

<!ELEMENT alarm (title, details+, action, contact)>
<!ELEMENT details (general, level+)>
<!ELEMENT contact ((firstname, lastname)?, email?, phone?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT general (#PCDATA)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST level
	severity CDATA #REQUIRED
>
<!ATTLIST alarm
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation CDATA "resource/fwAlarmHelp.xsd"
>
<!ATTLIST level
	severity CDATA #REQUIRED
>

=== echeu/wincc-srtm/SRTM_Monitor_EC-01/fwComps/help/en_US.utf8/AlarmHelp/fwAlarmHandlingDefault.xml
<?xml version="1.0"?>
<!--
(c) Copyright CERN 2005. All rights not expressly granted are reserved.
icecontrols.support@cern.ch

SPDX-License-Identifier: LGPL-3.0-only
-->

<!DOCTYPE alarm SYSTEM "resource/fwAlarmHelp.dtd">
<?xml-stylesheet type="text/xsl" href="resource/fwAlarmHelpStylesheet.xsl"?>
<alarm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resource/fwAlarmHelp.xsd">
	<title>Alert Title</title>
	<details>
		<general>No alarm help has been defined for this alarm. This is a generic JCOP Framework page that provides basic descriptions of the alarm severities.</general>
		<level severity="Warning">An alarm level which indicates an undesired condition. In such a case there is no impact on the physics data quality and no immediate intervention is required.</level>
		<level severity="Error">An alarm level which indicates an undesired condition for which action is required. In such a case there is a risk of an unwanted impact on the physics data quality or risk to the detector.</level>
		<level severity="Fatal">An alarm condition for which immediate intervention is required.</level>
	</details>
	<action>None defined</action>
	<contact>
		<firstname></firstname>
		<lastname></lastname>
		<email></email>
		<phone></phone>
	</contact>
</alarm>
